In [2]:
# pip install cvxpy
import cvxpy
import numpy

In [ ]:
# Construct the problem.
U
V
F
la0
laf0
lamin
lamax
lafmin
lafmax
la = cvxpy.Variable(n) # n = length of λ: 18121
laf = cvxpy.Variable(n) # n = length of λf: 4318
objective = cvxpy.Minimize(cvxpy.sum_squares(la - la0) + cvxpy.sum_squares(laf-laf0))
constraints = [lamin <= la, la <= lamax, lafmin <= laf, laf <= lafmax, la * (U - V) + laf * F == 0]
prob = cvxpy.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for λ is stored in `λ.value`.
print(la.value)
print(laf.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print(constraints[0].dual_value) # 0 to 4

In [4]:
dir(cvxpy)
help(cvxpy.sum_squares)

Help on function sum_squares in module cvxpy.atoms.sum_squares:

sum_squares(expr)
    The sum of the squares of the entries.
    
    Parameters
    ----------
    expr: Expression
        The expression to take the sum of squares of.
    
    Returns
    -------
    Expression
        An expression representing the sum of squares.



In [17]:
U = numpy.array([[1,4],
                 [0,4]])
V = numpy.array([[4,6],
                 [2,5]])
F = numpy.array([[6,56],
                 [20,8]])
la0 = [0.5,0.75]
laf0 = [0.3,0.9]
lamin = [-1]
lamax = [1]
lafmin = [0]
lafmax = [1]
la = cvxpy.Variable(2)
laf = cvxpy.Variable(2)
objective = cvxpy.Minimize(cvxpy.sum_squares((la - la0)/la0) + cvxpy.sum_squares((laf-laf0)/laf0))
constraints = [lamin <= la, la <= lamax, lafmin <= laf, laf <= lafmax, la * (U - V) + laf * F == 0]
prob = cvxpy.Problem(objective, constraints)

result = prob.solve()
print(la.value)
print(laf.value)
print(constraints[0].dual_value)

[0.5452479  0.80760463]
[0.01115148 0.15920221]
[0. 0.]


In [18]:
la.value @ U + laf.value @ F

array([3.79620088, 7.30951057])

In [19]:
la.value @ V

array([3.79620088, 7.30951057])

In [12]:
from scipy.optimize import minimize
import scipy.optimize
import numpy

In [13]:
def objective(x):
    x1 = x[0]
    x2 = x[1]
    x3 = x[2]
    x4 = x[3]
    return x1*x4*(x1+x2+x3)+x3
def constraint1(x):
    return x[0]*x[1]*x[2]*x[3]-25.0
def constraint2(x):
    sum_sq = 40
    for i in range(4):
        sum_sq = sum_sq - x[i]**2
    return sum_sq
x0 = [1,5,5,1]
print(objective(x0))
b = (1.0,5.0)
bnds = (b,b,b,b)
con1 = {'type':'ineq', 'fun': constraint1}
con2 = {'type':'eq', 'fun': constraint2}
cons = [con1, con2]
sol = minimize(objective, x0, method='SLSQP', bounds=bnds, constraints=cons)
print(sol)

16
     fun: 17.01401724563517
     jac: array([14.57227015,  1.37940764,  2.37940764,  9.56415057])
 message: 'Optimization terminated successfully.'
    nfev: 30
     nit: 5
    njev: 5
  status: 0
 success: True
       x: array([1.        , 4.7429961 , 3.82115462, 1.37940765])


In [14]:
U = numpy.array([[1,4],
                 [0,4]])
V = numpy.array([[4,6],
                 [2,5]])
F = numpy.array([[6,56],
                 [20,8]])
la0 = [0.5,0.75]
laf0 = [0.3,0.9]
x0 = [la0,laf0]
def objective (x):
    return numpy.sum(((x[0] - x0[0])/x0[0])**2) + numpy.sum(((x[1] - x0[1])/x0[1])**2)
def constraint(x):
    return x[0] * (U - V) + x[1] * F

In [15]:
b = (-1,1)
bnds = ((b, b), (b, b))
con1 = {'type':'eq', 'fun': constraint}

In [16]:
sol = minimize(objective, x0, method = 'SLSQP', bounds = bnds, constraints = con1)

IndexError: SLSQP Error: the length of bounds is not compatible with that of x0.

In [20]:
print(sol)

NameError: name 'sol' is not defined

In [17]:
print(sol.x)

[1.         4.7429961  3.82115462 1.37940765]
